export const initialBoardWhite = [
  [
    "blackKingRook",
    "blackKingKnight",
    "blackKingBishop",
    "blackKing",
    "blackQueen",
    "blackQueenBishop",
    "blackQueenKnight",
    "blackQueenRook",
  ],
  [
    "blackPawn",
    "blackPawn",
    "blackPawn",
    "blackPawn",
    "blackPawn",
    "blackPawn",
    "blackPawn",
    "blackPawn",
  ],
  ["", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", ""],
  [
    "whitePawn",
    "whitePawn",
    "whitePawn",
    "whitePawn",
    "whitePawn",
    "whitePawn",
    "whitePawn",
    "whitePawn",
  ],
  [
    "whiteKingRook",
    "whiteKingKnight",
    "whiteKingBishop",
    "whiteKing",
    "whiteQueen",
    "whiteQueenBishop",
    "whiteQueenKnight",
    "whiteQueenRook",
  ],
];

export const initialBoardBlack = [
  [
    "whiteKingRook",
    "whiteKingKnight",
    "whiteKingBishop",
    "whiteKing",
    "whiteQueen",
    "whiteQueenBishop",
    "whiteQueenKnight",
    "whiteQueenRook",
  ],
  [
    "whitePawn",
    "whitePawn",
    "whitePawn",
    "whitePawn",
    "whitePawn",
    "whitePawn",
    "whitePawn",
    "whitePawn",
  ],
  ["", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", ""],
  [
    "blackPawn",
    "blackPawn",
    "blackPawn",
    "blackPawn",
    "blackPawn",
    "blackPawn",
    "blackPawn",
    "blackPawn",
  ],
  [
    "blackKingRook",
    "blackKingKnight",
    "blackKingBishop",
    "blackKing",
    "blackQueen",
    "blackQueenBishop",
    "blackQueenKnight",
    "blackQueenRook",
  ],
];
